const qs=s=>document.querySelector(s),qsa=s=>[...document.querySelectorAll(s)];
qs("#year").textContent=new Date().getFullYear();
const navToggle=qs("#navToggle"),navLinks=qs("#navLinks");
navToggle?.addEventListener("click",()=>{const open=navLinks.classList.toggle("open");navToggle.setAttribute("aria-expanded",open)});
qsa(".nav-links a").forEach(a=>a.addEventListener("click",()=>navLinks.classList.remove("open")));
const state={running:false,stopped:false,manualOff:false,progress:0,target:60,ramp:12,hold:4,c1:24.2,c2:24.0,air:25.1,elapsed:0,cycle:"DEMO-001",samples:[]};
const els={c1:qs("#concrete1"),c2:qs("#concrete2"),air:qs("#chamberAir"),target:qs("#targetTemp"),trend1:qs("#trend1"),trend2:qs("#trend2"),progress:qs("#progressFill"),pct:qs("#progressPct"),stage:qs("#stageLabel"),elapsed:qs("#elapsed"),remaining:qs("#remaining"),steam:qs("#steamState"),lamp:qs("#steamLamp"),status:qs("#overallStatus"),log:qs("#logStatus"),mode:qs("#modeLabel"),cycle:qs("#cycleRef"),chart:qs("#trendChart")};
function fmtTime(sec){sec=Math.max(0,Math.floor(sec));const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=sec%60;return[h,m,s].map(v=>String(v).padStart(2,"0")).join(":")}
function stageFor(p){if(!state.running&&state.stopped)return"STOPPED";if(!state.running)return"READY";if(p<10)return"PREHEAT";if(p<48)return"RAMP";if(p<84)return"HOLD";return"COOLDOWN"}
function steamDemand(){if(!state.running||state.manualOff)return false;const st=stageFor(state.progress);if(st==="COOLDOWN")return false;if(st==="PREHEAT"||st==="RAMP")return true;return((state.c1+state.c2)/2)<state.target+.25}
function updateHMI(){const p=Math.min(100,state.progress),stage=stageFor(p),steamOn=steamDemand();els.c1.textContent=state.c1.toFixed(1);els.c2.textContent=state.c2.toFixed(1);els.air.textContent=state.air.toFixed(1);els.target.textContent=state.target.toFixed(1);els.trend1.textContent=state.running?"↗ live trend":"— stable";els.trend2.textContent=state.running?"↗ live trend":"— stable";els.progress.style.width=p+"%";els.pct.textContent=Math.round(p)+"%";els.stage.textContent=stage;els.elapsed.textContent=fmtTime(state.elapsed);els.remaining.textContent=fmtTime(Math.max(0,6*3600-state.elapsed));els.steam.textContent=steamOn?"ON":"OFF";els.steam.classList.toggle("on",steamOn);els.lamp.classList.toggle("on",steamOn);els.status.textContent=state.running?"STATUS: CURING":(state.stopped?"STATUS: STOPPED":"STATUS: READY");els.status.style.color=state.stopped?"#ef7676":"#62dc69";els.log.textContent=state.running?"ACTIVE":"READY";els.mode.textContent=state.manualOff?"MANUAL OFF":"AUTO MODE";els.cycle.textContent=state.cycle}
function simulateTick(){if(!state.running)return;state.progress+=.32;state.elapsed=(state.progress/100)*6*3600;const st=stageFor(state.progress),steam=steamDemand();if(st==="PREHEAT"){state.air+=steam?.18:-.03;state.c1+=.06;state.c2+=.055}else if(st==="RAMP"){state.air+=steam?.15:-.04;state.c1+=.13;state.c2+=.125}else if(st==="HOLD"){const err=state.target-((state.c1+state.c2)/2);state.air+=steam?.05:-.05;state.c1+=Math.max(-.025,Math.min(.05,err*.03))+(Math.random()-.5)*.015;state.c2+=Math.max(-.025,Math.min(.05,err*.028))+(Math.random()-.5)*.015}else{state.air-=.12;state.c1-=.055;state.c2-=.052}state.air=Math.max(20,Math.min(state.target+4.5,state.air));state.c1=Math.max(20,Math.min(state.target+1.2,state.c1));state.c2=Math.max(20,Math.min(state.target+1,state.c2));state.samples.push({c1:state.c1,c2:state.c2,air:state.air,target:state.target});if(state.samples.length>150)state.samples.shift();if(state.progress>=100){state.progress=100;state.running=false;state.manualOff=false}updateHMI();drawChart()}
function startDemo(){if(state.progress>=100||state.stopped)resetDemo();state.running=true;state.stopped=false;state.manualOff=false;if(state.samples.length===0)state.samples.push({c1:state.c1,c2:state.c2,air:state.air,target:state.target});updateHMI()}
function resetDemo(){Object.assign(state,{running:false,stopped:false,manualOff:false,progress:0,c1:24.2,c2:24.0,air:25.1,elapsed:0,samples:[]});updateHMI();drawChart()}
qs("#startDemo").addEventListener("click",startDemo);qs("#resetDemo").addEventListener("click",resetDemo);qs("#manualOff").addEventListener("click",()=>{if(!state.running)return;state.manualOff=!state.manualOff;qs("#manualOff").classList.toggle("active",state.manualOff);updateHMI()});qs("#stopCure").addEventListener("click",()=>{state.running=false;state.stopped=true;state.manualOff=false;updateHMI()});
function openModal(id){const m=qs(id);m.classList.add("open");m.setAttribute("aria-hidden","false")}function closeModals(){qsa(".hmi-modal").forEach(m=>{m.classList.remove("open");m.setAttribute("aria-hidden","true")})}
qs("#historyBtn").addEventListener("click",()=>openModal("#historyModal"));qs("#settingsBtn").addEventListener("click",()=>openModal("#settingsModal"));qsa("[data-close]").forEach(b=>b.addEventListener("click",closeModals));qsa(".hmi-modal").forEach(m=>m.addEventListener("click",e=>{if(e.target===m)closeModals()}));
qs("#saveSettings").addEventListener("click",()=>{state.target=Math.max(40,Math.min(80,parseFloat(qs("#settingTarget").value)||60));state.ramp=parseFloat(qs("#settingRamp").value)||12;state.hold=parseFloat(qs("#settingHold").value)||4;state.cycle=qs("#settingCycle").value.trim()||"DEMO-001";closeModals();updateHMI();drawChart()});
function drawChart(){const canvas=els.chart,rect=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1;canvas.width=Math.max(10,rect.width*dpr);canvas.height=Math.max(10,rect.height*dpr);const ctx=canvas.getContext("2d");ctx.scale(dpr,dpr);const w=rect.width,h=rect.height;ctx.clearRect(0,0,w,h);ctx.font=Math.max(6,w*.012)+"px Arial";ctx.fillStyle="#717b82";const tMin=20,tMax=75;for(let i=0;i<5;i++){const temp=30+i*10,y=h-10-(temp-tMin)/(tMax-tMin)*(h-24);ctx.strokeStyle="#30373d";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(30,y);ctx.lineTo(w-5,y);ctx.stroke();ctx.fillText(temp+"°",3,y+3)}const data=state.samples.length?state.samples:[{c1:29,c2:28,air:32,target:60},{c1:34,c2:33,air:39,target:60},{c1:43,c2:42,air:55,target:60},{c1:51,c2:50,air:66,target:60},{c1:57,c2:56,air:61,target:60},{c1:59,c2:58,air:59,target:60}];const plot=(key,color)=>{ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();data.forEach((p,i)=>{const x=30+(i/(Math.max(1,data.length-1)))*(w-38),y=h-10-(p[key]-tMin)/(tMax-tMin)*(h-24);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()};plot("c1","#56aff2");plot("c2","#63d957");plot("air","#e6a73f");plot("target","#c7cbca")}
window.addEventListener("resize",drawChart);setInterval(simulateTick,250);setInterval(()=>{qs("#hmiClock").textContent=new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})},1000);updateHMI();setTimeout(drawChart,50);
